# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bida1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1035, 631)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/bida.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_tien_ban = QtWidgets.QLabel(Form)
        self.label_tien_ban.setObjectName("label_tien_ban")
        self.verticalLayout_2.addWidget(self.label_tien_ban)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(30)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_tong_tg = QtWidgets.QLabel(Form)
        self.label_tong_tg.setStyleSheet("QLabel{\n"
"background-color: rgb(239, 41, 41);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_tong_tg.setObjectName("label_tong_tg")
        self.gridLayout_2.addWidget(self.label_tong_tg, 1, 4, 1, 1)
        self.label_tong_thoi_gian = QtWidgets.QLabel(Form)
        self.label_tong_thoi_gian.setStyleSheet("QLabel{\n"
"background-color: rgb(252, 233, 79)\n"
"}")
        self.label_tong_thoi_gian.setScaledContents(True)
        self.label_tong_thoi_gian.setWordWrap(False)
        self.label_tong_thoi_gian.setObjectName("label_tong_thoi_gian")
        self.gridLayout_2.addWidget(self.label_tong_thoi_gian, 0, 4, 1, 1)
        self.label_tg_dung = QtWidgets.QLabel(Form)
        self.label_tg_dung.setStyleSheet("QLabel{\n"
"background-color: rgb(239, 41, 41);\n"
"font: 57 18pt \"Ubuntu\";\n"
"}")
        self.label_tg_dung.setObjectName("label_tg_dung")
        self.gridLayout_2.addWidget(self.label_tg_dung, 1, 3, 1, 1)
        self.label_thanh_tien_gio = QtWidgets.QLabel(Form)
        self.label_thanh_tien_gio.setStyleSheet("QLabel{\n"
"background-color: rgb(239, 41, 41);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_thanh_tien_gio.setObjectName("label_thanh_tien_gio")
        self.gridLayout_2.addWidget(self.label_thanh_tien_gio, 1, 5, 1, 1)
        self.label_thoi_gian_dung = QtWidgets.QLabel(Form)
        self.label_thoi_gian_dung.setStyleSheet("QLabel{\n"
"background-color: rgb(252, 233, 79)\n"
"}")
        self.label_thoi_gian_dung.setScaledContents(True)
        self.label_thoi_gian_dung.setWordWrap(False)
        self.label_thoi_gian_dung.setObjectName("label_thoi_gian_dung")
        self.gridLayout_2.addWidget(self.label_thoi_gian_dung, 0, 3, 1, 1)
        self.label_tong_thoi_gian_2 = QtWidgets.QLabel(Form)
        self.label_tong_thoi_gian_2.setStyleSheet("QLabel{\n"
"background-color: rgb(252, 233, 79)\n"
"}")
        self.label_tong_thoi_gian_2.setScaledContents(True)
        self.label_tong_thoi_gian_2.setWordWrap(False)
        self.label_tong_thoi_gian_2.setObjectName("label_tong_thoi_gian_2")
        self.gridLayout_2.addWidget(self.label_tong_thoi_gian_2, 0, 5, 1, 1)
        self.label_gio = QtWidgets.QLabel(Form)
        self.label_gio.setStyleSheet("QLabel{\n"
"background-color: rgb(252, 233, 79);\n"
"font: ;\n"
"    font: 57 20pt \"Ubuntu\";\n"
"}")
        self.label_gio.setObjectName("label_gio")
        self.gridLayout_2.addWidget(self.label_gio, 0, 0, 1, 1)
        self.label_thoi_gian_bat_dau = QtWidgets.QLabel(Form)
        self.label_thoi_gian_bat_dau.setStyleSheet("QLabel{\n"
"background-color: rgb(252, 233, 79);\n"
"}")
        self.label_thoi_gian_bat_dau.setScaledContents(True)
        self.label_thoi_gian_bat_dau.setWordWrap(False)
        self.label_thoi_gian_bat_dau.setObjectName("label_thoi_gian_bat_dau")
        self.gridLayout_2.addWidget(self.label_thoi_gian_bat_dau, 0, 2, 1, 1)
        self.lcd_gio = QtWidgets.QLCDNumber(Form)
        self.lcd_gio.setStyleSheet("QLCDNumber{\n"
"background-color:rgb(204, 0, 0);\n"
"font: 57 18pt \"Ubuntu\";\n"
"}")
        self.lcd_gio.setDigitCount(10)
        self.lcd_gio.setObjectName("lcd_gio")
        self.gridLayout_2.addWidget(self.lcd_gio, 1, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 1, 1, 1, 1)
        self.label_tg_bat_dau = QtWidgets.QLabel(Form)
        self.label_tg_bat_dau.setStyleSheet("QLabel{\n"
"background-color: rgb(239, 41, 41);\n"
"font: 57 18pt \"Ubuntu\";\n"
"}")
        self.label_tg_bat_dau.setObjectName("label_tg_bat_dau")
        self.gridLayout_2.addWidget(self.label_tg_bat_dau, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_bdtg = QtWidgets.QPushButton(Form)
        self.pushButton_bdtg.setObjectName("pushButton_bdtg")
        self.horizontalLayout_2.addWidget(self.pushButton_bdtg)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.pushButton_dung = QtWidgets.QPushButton(Form)
        self.pushButton_dung.setObjectName("pushButton_dung")
        self.horizontalLayout_2.addWidget(self.pushButton_dung)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.pushButton_xoa = QtWidgets.QPushButton(Form)
        self.pushButton_xoa.setObjectName("pushButton_xoa")
        self.horizontalLayout_2.addWidget(self.pushButton_xoa)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_image_bida = QtWidgets.QLabel(Form)
        self.label_image_bida.setText("")
        self.label_image_bida.setPixmap(QtGui.QPixmap("../../../Downloads/bida.jpeg"))
        self.label_image_bida.setScaledContents(True)
        self.label_image_bida.setObjectName("label_image_bida")
        self.horizontalLayout_4.addWidget(self.label_image_bida)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 5)
        self.horizontalLayout_4.setStretch(2, 5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setStyleSheet("QLabel{\n"
"background-color: rgb(252, 233, 79);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 4, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_12.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_3.addWidget(self.lineEdit_12, 2, 3, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_14.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_3.addWidget(self.lineEdit_14, 3, 3, 1, 1)
        self.checkBox_mi_tom_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_mi_tom_2.setStyleSheet("QCheckBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.checkBox_mi_tom_2.setObjectName("checkBox_mi_tom_2")
        self.gridLayout_3.addWidget(self.checkBox_mi_tom_2, 1, 0, 1, 1)
        self.spinBox_sl_mi_tom_2 = QtWidgets.QSpinBox(Form)
        self.spinBox_sl_mi_tom_2.setStyleSheet("QSpinBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.spinBox_sl_mi_tom_2.setObjectName("spinBox_sl_mi_tom_2")
        self.gridLayout_3.addWidget(self.spinBox_sl_mi_tom_2, 1, 2, 1, 1)
        self.lineEdit_gia_heniken_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_gia_heniken_2.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_gia_heniken_2.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_gia_heniken_2.setObjectName("lineEdit_gia_heniken_2")
        self.gridLayout_3.addWidget(self.lineEdit_gia_heniken_2, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setStyleSheet("QLabel{\n"
"background-color: rgb(252, 233, 79);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 1, 1, 1)
        self.spinBox_sl_heniken_2 = QtWidgets.QSpinBox(Form)
        self.spinBox_sl_heniken_2.setStyleSheet("QSpinBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.spinBox_sl_heniken_2.setObjectName("spinBox_sl_heniken_2")
        self.gridLayout_3.addWidget(self.spinBox_sl_heniken_2, 4, 2, 1, 1)
        self.checkBox_sua_nuti_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_sua_nuti_2.setStyleSheet("QCheckBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.checkBox_sua_nuti_2.setObjectName("checkBox_sua_nuti_2")
        self.gridLayout_3.addWidget(self.checkBox_sua_nuti_2, 2, 0, 1, 1)
        self.spinBox_sl_nuti_2 = QtWidgets.QSpinBox(Form)
        self.spinBox_sl_nuti_2.setStyleSheet("QSpinBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.spinBox_sl_nuti_2.setObjectName("spinBox_sl_nuti_2")
        self.gridLayout_3.addWidget(self.spinBox_sl_nuti_2, 2, 2, 1, 1)
        self.label_tien_mi_tom_2 = QtWidgets.QLabel(Form)
        self.label_tien_mi_tom_2.setStyleSheet("QLabel\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.label_tien_mi_tom_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_tien_mi_tom_2.setObjectName("label_tien_mi_tom_2")
        self.gridLayout_3.addWidget(self.label_tien_mi_tom_2, 1, 4, 1, 1)
        self.lineEdit_gia_nuti_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_gia_nuti_2.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_gia_nuti_2.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_gia_nuti_2.setObjectName("lineEdit_gia_nuti_2")
        self.gridLayout_3.addWidget(self.lineEdit_gia_nuti_2, 2, 1, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_15.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_3.addWidget(self.lineEdit_15, 5, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setStyleSheet("QLabel{\n"
"background-color: rgb(252, 233, 79);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_4.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 1, 3, 1, 1)
        self.label_tien_nuti_2 = QtWidgets.QLabel(Form)
        self.label_tien_nuti_2.setStyleSheet("QLabel\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.label_tien_nuti_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_tien_nuti_2.setObjectName("label_tien_nuti_2")
        self.gridLayout_3.addWidget(self.label_tien_nuti_2, 2, 4, 1, 1)
        self.spinBox_sl_nha_dam_2 = QtWidgets.QSpinBox(Form)
        self.spinBox_sl_nha_dam_2.setStyleSheet("QSpinBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.spinBox_sl_nha_dam_2.setObjectName("spinBox_sl_nha_dam_2")
        self.gridLayout_3.addWidget(self.spinBox_sl_nha_dam_2, 3, 2, 1, 1)
        self.lineEdit_gia_mi_tom_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_gia_mi_tom_2.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_gia_mi_tom_2.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_gia_mi_tom_2.setObjectName("lineEdit_gia_mi_tom_2")
        self.gridLayout_3.addWidget(self.lineEdit_gia_mi_tom_2, 1, 1, 1, 1)
        self.checkBox_heniken_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_heniken_2.setStyleSheet("QCheckBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.checkBox_heniken_2.setObjectName("checkBox_heniken_2")
        self.gridLayout_3.addWidget(self.checkBox_heniken_2, 4, 0, 1, 1)
        self.checkBox_tiger_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_tiger_2.setStyleSheet("QCheckBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.checkBox_tiger_2.setObjectName("checkBox_tiger_2")
        self.gridLayout_3.addWidget(self.checkBox_tiger_2, 5, 0, 1, 1)
        self.lineEdit_gia_nha_dam_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_gia_nha_dam_2.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_gia_nha_dam_2.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_gia_nha_dam_2.setObjectName("lineEdit_gia_nha_dam_2")
        self.gridLayout_3.addWidget(self.lineEdit_gia_nha_dam_2, 3, 1, 1, 1)
        self.spinBox_sl_tiger_2 = QtWidgets.QSpinBox(Form)
        self.spinBox_sl_tiger_2.setStyleSheet("QSpinBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.spinBox_sl_tiger_2.setObjectName("spinBox_sl_tiger_2")
        self.gridLayout_3.addWidget(self.spinBox_sl_tiger_2, 5, 2, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_13.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_3.addWidget(self.lineEdit_13, 4, 3, 1, 1)
        self.label_tien_tiger_2 = QtWidgets.QLabel(Form)
        self.label_tien_tiger_2.setStyleSheet("QLabel\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.label_tien_tiger_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_tien_tiger_2.setObjectName("label_tien_tiger_2")
        self.gridLayout_3.addWidget(self.label_tien_tiger_2, 5, 4, 1, 1)
        self.label_tien_heniken_2 = QtWidgets.QLabel(Form)
        self.label_tien_heniken_2.setStyleSheet("QLabel\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.label_tien_heniken_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_tien_heniken_2.setObjectName("label_tien_heniken_2")
        self.gridLayout_3.addWidget(self.label_tien_heniken_2, 4, 4, 1, 1)
        self.label_tien_nha_dam_2 = QtWidgets.QLabel(Form)
        self.label_tien_nha_dam_2.setStyleSheet("QLabel\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.label_tien_nha_dam_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_tien_nha_dam_2.setObjectName("label_tien_nha_dam_2")
        self.gridLayout_3.addWidget(self.label_tien_nha_dam_2, 3, 4, 1, 1)
        self.checkBox_nha_dam_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_nha_dam_2.setStyleSheet("QCheckBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.checkBox_nha_dam_2.setObjectName("checkBox_nha_dam_2")
        self.gridLayout_3.addWidget(self.checkBox_nha_dam_2, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setStyleSheet("QLabel{\n"
"background-color: rgb(252, 233, 79);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setStyleSheet("QLabel{\n"
"background-color: rgb(252, 233, 79);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 3, 1, 1)
        self.lineEdit_gia_tiger_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_gia_tiger_2.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_gia_tiger_2.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_gia_tiger_2.setObjectName("lineEdit_gia_tiger_2")
        self.gridLayout_3.addWidget(self.lineEdit_gia_tiger_2, 5, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_gia_nha_dam = QtWidgets.QLineEdit(Form)
        self.lineEdit_gia_nha_dam.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_gia_nha_dam.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_gia_nha_dam.setObjectName("lineEdit_gia_nha_dam")
        self.gridLayout.addWidget(self.lineEdit_gia_nha_dam, 3, 1, 1, 1)
        self.spinBox_sl_nuti = QtWidgets.QSpinBox(Form)
        self.spinBox_sl_nuti.setStyleSheet("QSpinBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.spinBox_sl_nuti.setObjectName("spinBox_sl_nuti")
        self.gridLayout.addWidget(self.spinBox_sl_nuti, 2, 2, 1, 1)
        self.lineEdit_gia_mi_tom = QtWidgets.QLineEdit(Form)
        self.lineEdit_gia_mi_tom.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_gia_mi_tom.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_gia_mi_tom.setObjectName("lineEdit_gia_mi_tom")
        self.gridLayout.addWidget(self.lineEdit_gia_mi_tom, 1, 1, 1, 1)
        self.spinBox_sl_heniken = QtWidgets.QSpinBox(Form)
        self.spinBox_sl_heniken.setStyleSheet("QSpinBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.spinBox_sl_heniken.setObjectName("spinBox_sl_heniken")
        self.gridLayout.addWidget(self.spinBox_sl_heniken, 4, 2, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_9.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 3, 3, 1, 1)
        self.label_tien_heniken = QtWidgets.QLabel(Form)
        self.label_tien_heniken.setStyleSheet("QLabel\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.label_tien_heniken.setTextFormat(QtCore.Qt.AutoText)
        self.label_tien_heniken.setObjectName("label_tien_heniken")
        self.gridLayout.addWidget(self.label_tien_heniken, 4, 4, 1, 1)
        self.label_tien_nha_dam = QtWidgets.QLabel(Form)
        self.label_tien_nha_dam.setStyleSheet("QLabel\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.label_tien_nha_dam.setTextFormat(QtCore.Qt.AutoText)
        self.label_tien_nha_dam.setObjectName("label_tien_nha_dam")
        self.gridLayout.addWidget(self.label_tien_nha_dam, 3, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setStyleSheet("QLabel{\n"
"background-color: rgb(252, 233, 79);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 4, 1, 1)
        self.label_tien_mi_tom = QtWidgets.QLabel(Form)
        self.label_tien_mi_tom.setStyleSheet("QLabel\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.label_tien_mi_tom.setTextFormat(QtCore.Qt.AutoText)
        self.label_tien_mi_tom.setObjectName("label_tien_mi_tom")
        self.gridLayout.addWidget(self.label_tien_mi_tom, 1, 4, 1, 1)
        self.checkBox_sua_nuti = QtWidgets.QCheckBox(Form)
        self.checkBox_sua_nuti.setStyleSheet("QCheckBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.checkBox_sua_nuti.setObjectName("checkBox_sua_nuti")
        self.gridLayout.addWidget(self.checkBox_sua_nuti, 2, 0, 1, 1)
        self.checkBox_heniken = QtWidgets.QCheckBox(Form)
        self.checkBox_heniken.setStyleSheet("QCheckBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.checkBox_heniken.setObjectName("checkBox_heniken")
        self.gridLayout.addWidget(self.checkBox_heniken, 4, 0, 1, 1)
        self.label_tien_nuti = QtWidgets.QLabel(Form)
        self.label_tien_nuti.setStyleSheet("QLabel\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.label_tien_nuti.setTextFormat(QtCore.Qt.AutoText)
        self.label_tien_nuti.setObjectName("label_tien_nuti")
        self.gridLayout.addWidget(self.label_tien_nuti, 2, 4, 1, 1)
        self.checkBox_mi_tom = QtWidgets.QCheckBox(Form)
        self.checkBox_mi_tom.setStyleSheet("QCheckBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.checkBox_mi_tom.setObjectName("checkBox_mi_tom")
        self.gridLayout.addWidget(self.checkBox_mi_tom, 1, 0, 1, 1)
        self.checkBox_tiger = QtWidgets.QCheckBox(Form)
        self.checkBox_tiger.setStyleSheet("QCheckBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.checkBox_tiger.setObjectName("checkBox_tiger")
        self.gridLayout.addWidget(self.checkBox_tiger, 5, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_10.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 4, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setStyleSheet("QLabel{\n"
"background-color: rgb(252, 233, 79);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.label_tien_tiger = QtWidgets.QLabel(Form)
        self.label_tien_tiger.setStyleSheet("QLabel\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.label_tien_tiger.setTextFormat(QtCore.Qt.AutoText)
        self.label_tien_tiger.setObjectName("label_tien_tiger")
        self.gridLayout.addWidget(self.label_tien_tiger, 5, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setStyleSheet("QLabel{\n"
"background-color: rgb(252, 233, 79);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.spinBox_sl_tiger = QtWidgets.QSpinBox(Form)
        self.spinBox_sl_tiger.setStyleSheet("QSpinBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.spinBox_sl_tiger.setObjectName("spinBox_sl_tiger")
        self.gridLayout.addWidget(self.spinBox_sl_tiger, 5, 2, 1, 1)
        self.spinBox_sl_nha_dam = QtWidgets.QSpinBox(Form)
        self.spinBox_sl_nha_dam.setStyleSheet("QSpinBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.spinBox_sl_nha_dam.setObjectName("spinBox_sl_nha_dam")
        self.gridLayout.addWidget(self.spinBox_sl_nha_dam, 3, 2, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_11.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 5, 3, 1, 1)
        self.checkBox_nha_dam = QtWidgets.QCheckBox(Form)
        self.checkBox_nha_dam.setStyleSheet("QCheckBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.checkBox_nha_dam.setObjectName("checkBox_nha_dam")
        self.gridLayout.addWidget(self.checkBox_nha_dam, 3, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_3.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 3, 1, 1)
        self.lineEdit_gia_nuti = QtWidgets.QLineEdit(Form)
        self.lineEdit_gia_nuti.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_gia_nuti.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_gia_nuti.setObjectName("lineEdit_gia_nuti")
        self.gridLayout.addWidget(self.lineEdit_gia_nuti, 2, 1, 1, 1)
        self.spinBox_sl_mi_tom = QtWidgets.QSpinBox(Form)
        self.spinBox_sl_mi_tom.setStyleSheet("QSpinBox\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.spinBox_sl_mi_tom.setObjectName("spinBox_sl_mi_tom")
        self.gridLayout.addWidget(self.spinBox_sl_mi_tom, 1, 2, 1, 1)
        self.lineEdit_gia_heniken = QtWidgets.QLineEdit(Form)
        self.lineEdit_gia_heniken.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_gia_heniken.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_gia_heniken.setObjectName("lineEdit_gia_heniken")
        self.gridLayout.addWidget(self.lineEdit_gia_heniken, 4, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_8.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 2, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setStyleSheet("QLabel{\n"
"background-color: rgb(252, 233, 79);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setStyleSheet("QLabel{\n"
"background-color: rgb(252, 233, 79);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_gia_tiger = QtWidgets.QLineEdit(Form)
        self.lineEdit_gia_tiger.setMinimumSize(QtCore.QSize(108, 24))
        self.lineEdit_gia_tiger.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_gia_tiger.setObjectName("lineEdit_gia_tiger")
        self.gridLayout.addWidget(self.lineEdit_gia_tiger, 5, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_thanh_tien_thuc_don_2 = QtWidgets.QLabel(Form)
        self.label_thanh_tien_thuc_don_2.setStyleSheet("QLabel{\n"
"background-color: rgb(239, 41, 41);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_thanh_tien_thuc_don_2.setObjectName("label_thanh_tien_thuc_don_2")
        self.gridLayout_4.addWidget(self.label_thanh_tien_thuc_don_2, 3, 3, 1, 1)
        self.label_thanh_tien_thuc_don_5 = QtWidgets.QLabel(Form)
        self.label_thanh_tien_thuc_don_5.setStyleSheet("QLabel{\n"
"background-color: rgb(239, 41, 41);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_thanh_tien_thuc_don_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_thanh_tien_thuc_don_5.setWordWrap(True)
        self.label_thanh_tien_thuc_don_5.setObjectName("label_thanh_tien_thuc_don_5")
        self.gridLayout_4.addWidget(self.label_thanh_tien_thuc_don_5, 3, 6, 1, 1)
        self.lineEdit_gia_mi_tom_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_gia_mi_tom_4.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_gia_mi_tom_4.setObjectName("lineEdit_gia_mi_tom_4")
        self.gridLayout_4.addWidget(self.lineEdit_gia_mi_tom_4, 5, 3, 1, 1)
        self.lineEdit_gia_mi_tom_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_gia_mi_tom_3.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(101, 201, 226);\n"
"font: 57 10pt \"Ubuntu\";\n"
"}")
        self.lineEdit_gia_mi_tom_3.setObjectName("lineEdit_gia_mi_tom_3")
        self.gridLayout_4.addWidget(self.lineEdit_gia_mi_tom_3, 5, 7, 1, 1)
        self.label_thanh_tien_thuc_don_6 = QtWidgets.QLabel(Form)
        self.label_thanh_tien_thuc_don_6.setStyleSheet("QLabel{\n"
"background-color: rgb(239, 41, 41);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_thanh_tien_thuc_don_6.setObjectName("label_thanh_tien_thuc_don_6")
        self.gridLayout_4.addWidget(self.label_thanh_tien_thuc_don_6, 3, 7, 1, 1)
        self.label_thanh_tien_thuc_don_4 = QtWidgets.QLabel(Form)
        self.label_thanh_tien_thuc_don_4.setStyleSheet("QLabel{\n"
"background-color: rgb(239, 41, 41);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_thanh_tien_thuc_don_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_thanh_tien_thuc_don_4.setWordWrap(True)
        self.label_thanh_tien_thuc_don_4.setObjectName("label_thanh_tien_thuc_don_4")
        self.gridLayout_4.addWidget(self.label_thanh_tien_thuc_don_4, 3, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 2, 0, 1, 1)
        self.label_thanh_tien_thuc_don_3 = QtWidgets.QLabel(Form)
        self.label_thanh_tien_thuc_don_3.setStyleSheet("QLabel{\n"
"background-color: rgb(239, 41, 41);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.label_thanh_tien_thuc_don_3.setObjectName("label_thanh_tien_thuc_don_3")
        self.gridLayout_4.addWidget(self.label_thanh_tien_thuc_don_3, 3, 5, 1, 1)
        self.pushButton_tong_tien_thuc_don_3 = QtWidgets.QPushButton(Form)
        self.pushButton_tong_tien_thuc_don_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(252, 233, 79)\n"
"}")
        self.pushButton_tong_tien_thuc_don_3.setObjectName("pushButton_tong_tien_thuc_don_3")
        self.gridLayout_4.addWidget(self.pushButton_tong_tien_thuc_don_3, 5, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 2, 1, 1, 1)
        self.pushButton_xoa_2 = QtWidgets.QPushButton(Form)
        self.pushButton_xoa_2.setObjectName("pushButton_xoa_2")
        self.gridLayout_4.addWidget(self.pushButton_xoa_2, 0, 0, 1, 1)
        self.pushButton_tong_tien_thuc_don_4 = QtWidgets.QPushButton(Form)
        self.pushButton_tong_tien_thuc_don_4.setStyleSheet("QPushButton{\n"
"background-color: rgb(252, 233, 79)\n"
"}")
        self.pushButton_tong_tien_thuc_don_4.setObjectName("pushButton_tong_tien_thuc_don_4")
        self.gridLayout_4.addWidget(self.pushButton_tong_tien_thuc_don_4, 5, 6, 1, 1)
        self.pushButton_tong_tien_thuc_don_6 = QtWidgets.QPushButton(Form)
        self.pushButton_tong_tien_thuc_don_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(252, 233, 79)\n"
"}")
        self.pushButton_tong_tien_thuc_don_6.setObjectName("pushButton_tong_tien_thuc_don_6")
        self.gridLayout_4.addWidget(self.pushButton_tong_tien_thuc_don_6, 0, 5, 1, 1)
        self.pushButton_xoa_3 = QtWidgets.QPushButton(Form)
        self.pushButton_xoa_3.setObjectName("pushButton_xoa_3")
        self.gridLayout_4.addWidget(self.pushButton_xoa_3, 3, 2, 1, 1)
        self.pushButton_xoa_don = QtWidgets.QPushButton(Form)
        self.pushButton_xoa_don.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 101, 164)\n"
"}")
        self.pushButton_xoa_don.setIconSize(QtCore.QSize(10, 10))
        self.pushButton_xoa_don.setObjectName("pushButton_xoa_don")
        self.gridLayout_4.addWidget(self.pushButton_xoa_don, 0, 7, 1, 1)
        self.lineEdit_gia_mi_tom_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_gia_mi_tom_5.setStyleSheet("QLineEdit\n"
"{\n"
"background-color: rgb(239, 41, 41);\n"
"font: 57 13pt \"Ubuntu\";\n"
"}")
        self.lineEdit_gia_mi_tom_5.setObjectName("lineEdit_gia_mi_tom_5")
        self.gridLayout_4.addWidget(self.lineEdit_gia_mi_tom_5, 0, 6, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Bida"))
        self.label_tien_ban.setText(_translate("Form", "Tiền bàn(30k/ 1 giờ)"))
        self.label_tong_tg.setText(_translate("Form", "0"))
        self.label_tong_thoi_gian.setText(_translate("Form", "Tổng thời gian"))
        self.label_tg_dung.setText(_translate("Form", "00:00:00"))
        self.label_thanh_tien_gio.setText(_translate("Form", "0đ"))
        self.label_thoi_gian_dung.setText(_translate("Form", "Thời gian dừng"))
        self.label_tong_thoi_gian_2.setText(_translate("Form", "Thành tiền"))
        self.label_gio.setText(_translate("Form", "Giờ"))
        self.label_thoi_gian_bat_dau.setText(_translate("Form", "Thời gian bắt đầu"))
        self.label_tg_bat_dau.setText(_translate("Form", "00:00:00"))
        self.pushButton_bdtg.setText(_translate("Form", "Bắt đầu tính giờ"))
        self.pushButton_dung.setText(_translate("Form", "Dừng"))
        self.pushButton_xoa.setText(_translate("Form", "Xóa"))
        self.label.setText(_translate("Form", "THỰC ĐƠN"))
        self.label_10.setText(_translate("Form", "Thành tiền"))
        self.lineEdit_12.setText(_translate("Form", "Chai"))
        self.lineEdit_14.setText(_translate("Form", "Chai"))
        self.checkBox_mi_tom_2.setText(_translate("Form", "Mì Tôm"))
        self.lineEdit_gia_heniken_2.setText(_translate("Form", "8000đ"))
        self.label_11.setText(_translate("Form", "Giá"))
        self.checkBox_sua_nuti_2.setText(_translate("Form", "Sữa nutifood"))
        self.label_tien_mi_tom_2.setText(_translate("Form", "0đ"))
        self.lineEdit_gia_nuti_2.setText(_translate("Form", "8000đ"))
        self.lineEdit_15.setText(_translate("Form", "Lon"))
        self.label_6.setText(_translate("Form", "Tên món"))
        self.lineEdit_4.setText(_translate("Form", "Tô"))
        self.label_tien_nuti_2.setText(_translate("Form", "0đ"))
        self.lineEdit_gia_mi_tom_2.setText(_translate("Form", "8000đ"))
        self.checkBox_heniken_2.setText(_translate("Form", "Bia heniken"))
        self.checkBox_tiger_2.setText(_translate("Form", "Bia tiger"))
        self.lineEdit_gia_nha_dam_2.setText(_translate("Form", "8000đ"))
        self.lineEdit_13.setText(_translate("Form", "Lon"))
        self.label_tien_tiger_2.setText(_translate("Form", "0đ"))
        self.label_tien_heniken_2.setText(_translate("Form", "0đ"))
        self.label_tien_nha_dam_2.setText(_translate("Form", "0đ"))
        self.checkBox_nha_dam_2.setText(_translate("Form", "Nước nha đam"))
        self.label_8.setText(_translate("Form", "Số lượng"))
        self.label_9.setText(_translate("Form", "Đơn vị"))
        self.lineEdit_gia_tiger_2.setText(_translate("Form", "8000đ"))
        self.lineEdit_gia_nha_dam.setText(_translate("Form", "8000đ"))
        self.lineEdit_gia_mi_tom.setText(_translate("Form", "8000đ"))
        self.lineEdit_9.setText(_translate("Form", "Chai"))
        self.label_tien_heniken.setText(_translate("Form", "0đ"))
        self.label_tien_nha_dam.setText(_translate("Form", "0đ"))
        self.label_5.setText(_translate("Form", "Thành tiền"))
        self.label_tien_mi_tom.setText(_translate("Form", "0đ"))
        self.checkBox_sua_nuti.setText(_translate("Form", "Sữa nutifood"))
        self.checkBox_heniken.setText(_translate("Form", "Bia heniken"))
        self.label_tien_nuti.setText(_translate("Form", "0đ"))
        self.checkBox_mi_tom.setText(_translate("Form", "Mì Tôm"))
        self.checkBox_tiger.setText(_translate("Form", "Bia tiger"))
        self.lineEdit_10.setText(_translate("Form", "Lon"))
        self.label_7.setText(_translate("Form", "Đơn vị"))
        self.label_tien_tiger.setText(_translate("Form", "0đ"))
        self.label_4.setText(_translate("Form", "Số lượng"))
        self.lineEdit_11.setText(_translate("Form", "Lon"))
        self.checkBox_nha_dam.setText(_translate("Form", "Nước nha đam"))
        self.lineEdit_3.setText(_translate("Form", "Tô"))
        self.lineEdit_gia_nuti.setText(_translate("Form", "8000đ"))
        self.lineEdit_gia_heniken.setText(_translate("Form", "8000đ"))
        self.lineEdit_8.setText(_translate("Form", "Chai"))
        self.label_3.setText(_translate("Form", "Giá"))
        self.label_2.setText(_translate("Form", "Tên món"))
        self.lineEdit_gia_tiger.setText(_translate("Form", "8000đ"))
        self.label_thanh_tien_thuc_don_2.setText(_translate("Form", "0đ"))
        self.label_thanh_tien_thuc_don_5.setText(_translate("Form", "="))
        self.lineEdit_gia_mi_tom_4.setText(_translate("Form", "0đ"))
        self.lineEdit_gia_mi_tom_3.setText(_translate("Form", "0đ"))
        self.label_thanh_tien_thuc_don_6.setText(_translate("Form", "0đ"))
        self.label_thanh_tien_thuc_don_4.setText(_translate("Form", "+"))
        self.label_thanh_tien_thuc_don_3.setText(_translate("Form", "0đ"))
        self.pushButton_tong_tien_thuc_don_3.setText(_translate("Form", "Khách đưa: "))
        self.pushButton_xoa_2.setText(_translate("Form", "Thêm món"))
        self.pushButton_tong_tien_thuc_don_4.setText(_translate("Form", "Thối lại: "))
        self.pushButton_tong_tien_thuc_don_6.setText(_translate("Form", "Tiền thực đơn"))
        self.pushButton_xoa_3.setText(_translate("Form", "Tổng tiền"))
        self.pushButton_xoa_don.setText(_translate("Form", "Xóa đơn"))
        self.lineEdit_gia_mi_tom_5.setText(_translate("Form", "0đ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
