# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '06_Calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(576, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 616, 224))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.verticalLayoutWidget)
        self.calendarWidget.setMinimumSize(QtCore.QSize(614, 0))
        self.calendarWidget.setStyleSheet("  /*Tool button styles */\n"
"QCalendarWidget QToolButton {\n"
" \n"
" \n"
"height:20px;\n"
"width:40px;\n"
"color:white;\n"
"font-size:8px;\n"
"icon-size:20px,20px;\n"
"background-color:rgb(237, 212, 0);\n"
" \n"
" \n"
" \n"
"}\n"
" \n"
" \n"
" \n"
"  /* header row */\n"
"QCalendarWidget  QWidget{\n"
" \n"
"alternate-background-color:rgb(128,128,128)\n"
" \n"
" \n"
" \n"
"}\n"
" \n"
" \n"
"  /*normal days */\n"
"QCalendarWidget QAbstractItemView:enabled {\n"
" \n"
" \n"
"font-size:8px;\n"
"color:rgb(180,180,180);\n"
"background-color:white;\n"
"selection-background-color:rgb(64,64,64);\n"
"selection-color:rgb(0,100,0);\n"
" \n"
" \n"
" \n"
"}")
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.calendarWidget.setFixedSize(QtCore.QSize(400, 300))
        self.verticalLayout.addWidget(self.calendarWidget)

        self.calendarWidget.selectionChanged.connect(self.calendar_date)
        # setting fixed size

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calendar"))

    def calendar_date(self):
        date_selected = self.calendarWidget.selectedDate()
        print(str(date_selected.toPyDate()))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
